AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldLambda
      Runtime: python3.9
      Handler: hello_world.lambda_handler
      Role: arn:aws:iam::891376961526:role/LabRole
      Code:
        S3Bucket: scriptsforcft1
        S3Key: lambda_code/LambdaScript.zip
      Timeout: 15
      MemorySize: 128
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python313:1  # Replace with your region's ARN

  MyGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: DAC_GlueJob
      Role: arn:aws:iam::891376961526:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://scriptsforcft1/lambda_code/DAC_GlueJob_.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--job-language": "python"
      WorkerType: "Standard"
      NumberOfWorkers: 2

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: data---for1-glue1  # Ensure this is globally unique
 
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GlueTrigger
      Runtime: python3.13
      Handler: GlueTrigger.lambda_handler
      Role: arn:aws:iam::891376961526:role/LabRole
      Code:
        S3Bucket: scriptsforcft1
        S3Key: lambda_code/LambdaGlueScript.zip
      Timeout: 15
      MemorySize: 128
