AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldLambda
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::891376961526:role/LabRole
      Code:
        S3Bucket: scriptsforcft1
        S3Key: lambda_code/LambdaScript.zip
      Timeout: 15
      MemorySize: 128
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python313:1  # Replace with your region's ARN

  MyGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: Glue_dac
      Role: arn:aws:iam::891376961526:role/LabRole
      Command:
        Name: Glue_dac
        ScriptLocation: !Sub "s3://scriptsforcft1/lambda_code/DAC_GlueJob_.py"
        PythonVersion: "3"
      GlueVersion: "4.0"
      DefaultArguments:
        "--job-language": "python"
      WorkerType: "Standard"
      NumberOfWorkers: 2

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: data---for1-glue143
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv  # Trigger only when CSV files are uploaded
            Function: !GetAtt GlueTriggerFunction.Arn

  MyS3BucketLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GlueTriggerFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::data---for1-glue143

  GlueTriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GlueTrigger
      Runtime: python3.9
      Handler: glue_trigger.lambda_handler
      Role: arn:aws:iam::891376961526:role/LabRole
      Code:
        S3Bucket: scriptsforcft1
        S3Key: lambda_code/LambdaGlueScript.zip
      Timeout: 15
      MemorySize: 128
