AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldLambda
      Runtime: python3.9
      Handler: hello_world.lambda_handler
      Role: arn:aws:iam::891376961526:role/LabRole
      Code:
        S3Bucket: scriptsforcft1
        S3Key: lambda_code/hello_world.zip
      Timeout: 15
      MemorySize: 128
 MyGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: DAC_GlueJob
      Role: arn:aws:iam::891376961526:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://scriptsforcft1/lambda_code/DAC_GlueJob_.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--job-language": "python"
      WorkerType: "Standard"
      NumberOfWorkers: 2
