AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldLambda
      Runtime: python3.9
      Handler: hello_world.lambda_handler
      Role: arn:aws:iam::975049960469:role/LabRole
      Code:
        S3Bucket: scriptsforcft
        S3Key: lambda_code/hello_world.py
      Timeout: 15
      MemorySize: 128
